import type { OnboardingStep, OnboardingTourConfig } from './types'

const appConfigSteps: OnboardingStep[] = [
  // ========== Enter Config Page via Agent Card ==========
  {
    target: '[data-testid="app-card-first"]',
    content: 'onboarding.step18.description',
    title: 'onboarding.step18.title',
    placement: 'right',
    route: '/app/apps',
    advanceOnClick: true,
    waitForRouteChange: true,
    overlayClickAction: false,
  },
  // ========== Agent Config Page Navigation ==========
  {
    target: '[data-testid="agent-nav-orchestration"]',
    content: 'onboarding.step10a.description',
    title: 'onboarding.step10a.title',
    placement: 'right',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-nav-api"]',
    content: 'onboarding.step10b.description',
    title: 'onboarding.step10b.title',
    placement: 'right',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-nav-logs"]',
    content: 'onboarding.step10c.description',
    title: 'onboarding.step10c.title',
    placement: 'right',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-nav-monitor"]',
    content: 'onboarding.step10d.description',
    title: 'onboarding.step10d.title',
    placement: 'right',
    overlayClickAction: false,
  },
  // ========== Prompt & Variables ==========
  {
    target: '[data-testid="agent-prompt-section"]',
    content: 'onboarding.step11.description',
    title: 'onboarding.step11.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-prompt-ai-generate"]',
    content: 'onboarding.step11b.description',
    title: 'onboarding.step11b.title',
    placement: 'auto',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-variables-section"]',
    content: 'onboarding.step11c.description',
    title: 'onboarding.step11c.title',
    placement: 'left',
    overlayClickAction: false,
  },
  // ========== Knowledge Base & Tools ==========
  {
    target: '[data-testid="agent-kb-section"]',
    content: 'onboarding.step12.description',
    title: 'onboarding.step12.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-tools-section"]',
    content: 'onboarding.step13.description',
    title: 'onboarding.step13.title',
    placement: 'left',
    overlayClickAction: false,
  },
  // ========== Capabilities ==========
  {
    target: '[data-testid="agent-attachments-section"]',
    content: 'onboarding.step14b.description',
    title: 'onboarding.step14b.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-memory-section"]',
    content: 'onboarding.step14d.description',
    title: 'onboarding.step14d.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-image-generation-section"]',
    content: 'onboarding.step14e.description',
    title: 'onboarding.step14e.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-video-generation-section"]',
    content: 'onboarding.step14f.description',
    title: 'onboarding.step14f.title',
    placement: 'left',
    overlayClickAction: false,
  },
  // ========== Chat, Embed & Settings ==========
  {
    target: '[data-testid="agent-chat-button"]',
    content: 'onboarding.step17b.description',
    title: 'onboarding.step17b.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-embed-button"]',
    content: 'onboarding.step14g.description',
    title: 'onboarding.step14g.title',
    placement: 'bottom',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="embed-config-dialog"]',
    content: 'onboarding.step14g2.description',
    title: 'onboarding.step14g2.title',
    // Dialog target: bottom keeps the tooltip below the dialog content.
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-slot="dialog-close"]',
    content: 'onboarding.step14g3.description',
    title: 'onboarding.step14g3.title',
    placement: 'left',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-settings-button"]',
    content: 'onboarding.step14l.description',
    title: 'onboarding.step14l.title',
    placement: 'bottom',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="settings-icon-upload"]',
    content: 'onboarding.step14m.description',
    title: 'onboarding.step14m.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="settings-name-input"]',
    content: 'onboarding.step14n.description',
    title: 'onboarding.step14n.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="settings-description-input"]',
    content: 'onboarding.step14o.description',
    title: 'onboarding.step14o.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="settings-visibility-select"]',
    content: 'onboarding.step14p.description',
    title: 'onboarding.step14p.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="settings-model-select"]',
    content: 'onboarding.step14q.description',
    title: 'onboarding.step14q.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="settings-hide-tool-calls"]',
    content: 'onboarding.step14s.description',
    title: 'onboarding.step14s.title',
    placement: 'left',
    overlayClickAction: false,
  },
  // ========== Conversation Settings ==========
  {
    target: '[data-testid="settings-conversation-section"]',
    content: 'onboarding.step14t.description',
    title: 'onboarding.step14t.title',
    placement: 'left',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="settings-opening-message"]',
    content: 'onboarding.step14u.description',
    title: 'onboarding.step14u.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="settings-suggested-questions"]',
    content: 'onboarding.step14v.description',
    title: 'onboarding.step14v.title',
    placement: 'left',
    overlayClickAction: false,
  },
  {
    target: '[data-slot="sheet-close"]',
    content: 'onboarding.step14w.description',
    title: 'onboarding.step14w.title',
    placement: 'left',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  // ========== Save & Publish ==========
  {
    target: '[data-testid="agent-save-button"]',
    content: 'onboarding.step15.description',
    title: 'onboarding.step15.title',
    placement: 'bottom',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-publish-button"]',
    content: 'onboarding.step15b.description',
    title: 'onboarding.step15b.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-publish-button"]',
    content: 'onboarding.step16.description',
    title: 'onboarding.step16.title',
    placement: 'bottom',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-publish-confirm"]',
    content: 'onboarding.step16b.description',
    title: 'onboarding.step16b.title',
    placement: 'bottom',
    advanceOnClick: true,
    overlayClickAction: false,
  },
  {
    target: '[data-testid="agent-publish-button"]',
    content: 'onboarding.step16c.description',
    title: 'onboarding.step16c.title',
    placement: 'bottom',
    overlayClickAction: false,
  },
]

export const appConfigTourConfig: OnboardingTourConfig = {
  id: 'appConfig',
  title: 'onboarding.tourAppConfigTitle',
  description: 'onboarding.tourAppConfigDescription',
  steps: appConfigSteps,
  autoStart: false,
  prerequisites: ['appCreate'],
}
